### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by harshil6924** [tgisaturday/Seq2CNN#2]
Can you please guide me with, how i can obtain dataset to train the model?

**Comment by tgisaturday** [comment]
https://drive.google.com/drive/u/0/folders/0Bz8a_Dbh9Qhbfll6bVpmNUtUcFdjYmF2SEpmZUZUcVNiMUw1TWN6RDV3a0JHT3kxLVhVR2M

I found them in this google drive.

**Comment by harshil6924** [comment]
Thank you !
